version: "3"

services:
  bilibili-helper:
    image: superng6/bilibili-helper:latest
    container_name: bilibili-helper
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - TASK=1d
      - DEDEUSERID=1
      - SESSDATA=2
      - BILI_JCT=3
#     - SERVERPUSHKEY=token
      - CUSP=false
      - CRON=false
    volumes:
      - $PWD/config:/config
    restart: unless-stopped

    