name: Build Image x86_64

on:
  push:
    paths:
      - "ReleaseTag"
  repository_dispatch:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Set env
        run: |
          echo "TAG=$(cat ReleaseTag | head -n1)" >> $GITHUB_ENV
        shell: bash
      - name: Build tag
        run: |
          docker buildx build \
          --platform=linux/arm64 \
          --output "type=image,push=true" \
          --tag "superng6/bilbili-helper:${{ env.TAG }}" \
          --file Dockerfile .
      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag superng6/bilbili-helper:latest
