name: Build Image

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Set env
        id: set-version
        run: |
          echo "TAG=$(cat ReleaseTag | head -n1)" >> $GITHUB_ENV
          echo "::set-output name=status::success"
        shell: bash
      - name: Build dockerfile tag arm64
        if: steps.set-version.outputs.status == 'success'
        run: |
          docker buildx build \
            --platform=linux/arm64 \
            --output "type=image,push=true" \
            --tag "superng6/bilbili-helper:arm64-${{ env.TAG }}" \
            --file Dockerfile-arm64 .
      - name: Build dockerfile tag x86_64
        if: steps.set-version.outputs.status == 'success'
        run: |
          docker buildx build \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --tag "superng6/bilbili-helper:${{ env.TAG }}" \
            --file Dockerfile .
      - name: Build dockerfile arm64
        if: steps.set-version.outputs.status == 'success'
        run: |
          docker buildx build \
            --platform=linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile-arm64 . \
            --tag superng6/bilbili-helper:arm64-latest
      - name: Build dockerfile x86_64
        if: steps.set-version.outputs.status == 'success'
        run: |
          docker buildx build \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag superng6/bilbili-helper:latest
